name: Build Executable

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller netrunner-proxy.spec
    
    - name: Test executable
      run: |
        ./dist/netrunner-proxy.exe --help
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: netrunner-proxy-windows
        path: dist/netrunner-proxy.exe
    

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller netrunner-proxy.spec
    
    - name: Test executable
      run: |
        ./dist/netrunner-proxy --help
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: netrunner-proxy-macos
        path: dist/netrunner-proxy
    

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller netrunner-proxy.spec
    
    - name: Test executable
      run: |
        ./dist/netrunner-proxy --help
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: netrunner-proxy-linux
        path: dist/netrunner-proxy

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create archives and upload
      run: |
        # Create Windows zip
        cd artifacts/netrunner-proxy-windows
        zip netrunner-proxy-windows.zip netrunner-proxy.exe
        gh release upload ${{ github.ref_name }} netrunner-proxy-windows.zip --clobber
        cd ../..
        
        # Create macOS tar.gz
        cd artifacts/netrunner-proxy-macos
        tar -czf netrunner-proxy-macos.tar.gz netrunner-proxy
        gh release upload ${{ github.ref_name }} netrunner-proxy-macos.tar.gz --clobber
        cd ../..
        
        # Create Linux tar.gz
        cd artifacts/netrunner-proxy-linux
        tar -czf netrunner-proxy-linux.tar.gz netrunner-proxy
        gh release upload ${{ github.ref_name }} netrunner-proxy-linux.tar.gz --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}